import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { MemoryRouter } from "react-router-dom";
import { beforeEach, expect, test, vi } from "vitest";
import InterviewPrep from "./InterviewPrep";
const mocks=vi.hoisted(()=>({auth:vi.fn(),source:vi.fn(),variants:vi.fn(),build:vi.fn()}));
vi.mock("@/lib/AuthContext.jsx",()=>({useAuth:()=>mocks.auth()}));
vi.mock("@/components/DashboardLayout",()=>({DashboardLayout:({children}:{children:React.ReactNode})=><div>{children}</div>}));
vi.mock("@/lib/emails",()=>({fetchResumeVariants:()=>mocks.variants()}));
vi.mock("@/lib/interviewPrep",async()=>({...await vi.importActual("@/lib/interviewPrep"),fetchInterviewSource:(...args:unknown[])=>mocks.source(...args),buildInterviewPractice:(...args:unknown[])=>mocks.build(...args)}));
const logicalKey="0123456789abcdef",dedupeKey="fedcba9876543210",variantId="aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee";
const quote="Manage appointment scheduling and patient records.";
const posting=`Receptionist responsibilities at Example Health. ${quote} Maintain accurate information and support patients and visitors throughout the day.`;
const source={logicalKey,dedupeKey,sourceVersion:"a".repeat(64),company:"Example Health",role:"Receptionist",threadId:"thread",schedule:null,excerpts:[{id:"1",subject:"Invitation",sender:"Recruiter",text:"Interview at the clinic.",receivedAt:null}]};
const pack={sourceVersion:source.sourceVersion,resume:{id:variantId,name:"Front desk",version:"b".repeat(64)},postingVersion:"c".repeat(64),disclosure:"Practice prompts, not predictions of interview questions.",practice:[{id:"focus-one",quote,kind:"experience",question:"Walk through a real example.",guidance:"Only facts you can support.",askInterviewer:"How is success measured?",possibleExamples:["Managed appointment scheduling and patient records for a clinic."]}]};
beforeEach(()=>{vi.clearAllMocks();mocks.auth.mockReturnValue({user:{uid:"owner"}});mocks.source.mockResolvedValue(source);mocks.variants.mockResolvedValue({success:true,variants:[{id:variantId,name:"Front desk",isDefault:true},{id:"ffffffff-bbbb-4ccc-8ddd-eeeeeeeeeeee",name:"Other version"}]});mocks.build.mockResolvedValue(pack);});
function setup(client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}}),path=`/interview-prep?action=${logicalKey}&version=${dedupeKey}`){const ui=<QueryClientProvider client={client}><MemoryRouter initialEntries={[path]}><InterviewPrep/></MemoryRouter></QueryClientProvider>;return {...render(ui),client,ui};}
async function fill(){await screen.findByText("Example Health · Receptionist");await userEvent.selectOptions(screen.getByLabelText("Resume for this interview"),variantId);await userEvent.type(screen.getByLabelText("Posting for this role"),posting);await userEvent.type(screen.getByLabelText("Responsibilities or requirements to practice"),quote);}
async function build(){await userEvent.click(screen.getByRole("button",{name:"Build my practice"}));await screen.findByText("Walk through a real example.");}
test("even a default resume requires an explicit choice; no source means no guess",async()=>{setup();await screen.findByText("Example Health · Receptionist");expect(screen.getByLabelText("Resume for this interview")).toHaveValue("");expect(screen.getByRole("button",{name:"Build my practice"})).toBeDisabled();expect(screen.getByText(/Date and time are unconfirmed/)).toBeInTheDocument();expect(mocks.build).not.toHaveBeenCalled();});
test("build carries the exact task, invitation version, posting and selected resume",async()=>{setup();await fill();await build();expect(mocks.build).toHaveBeenCalledWith({logicalKey,dedupeKey,sourceVersion:source.sourceVersion,variantId,jobDescription:posting,focusAreas:[quote]});expect(screen.getByText(pack.disclosure)).toBeInTheDocument();await userEvent.click(screen.getByText("Possible examples from your selected resume"));expect(screen.getByText(pack.practice[0].possibleExamples[0])).toBeInTheDocument();});
test("inputs, pack and rehearsal notes survive navigation without silently rebuilding",async()=>{const page=setup();await fill();await build();await userEvent.type(screen.getByLabelText("What I did"),"I confirmed each appointment and updated the records.");page.unmount();setup(page.client);expect(await screen.findByLabelText("What I did")).toHaveValue("I confirmed each appointment and updated the records.");expect(screen.getByLabelText("Posting for this role")).toHaveValue(posting);expect(mocks.build).toHaveBeenCalledTimes(1);});
test("rebuilding cannot discard written notes without explicit reset acknowledgement",async()=>{setup();await fill();await build();await userEvent.type(screen.getByLabelText("Situation"),"A busy clinic morning.");const rebuild=screen.getByRole("button",{name:"Rebuild practice"});expect(rebuild).toBeDisabled();await userEvent.click(screen.getByLabelText(/I understand rebuilding replaces/));expect(rebuild).toBeEnabled();await userEvent.click(rebuild);await waitFor(()=>expect(screen.getByLabelText("Situation")).toHaveValue(""));});
test("new invitation fingerprint makes old practice unavailable for copying while retaining notes",async()=>{setup();await fill();await build();await userEvent.type(screen.getByLabelText("What I did"),"My actual contribution.");mocks.source.mockResolvedValue({...source,sourceVersion:"d".repeat(64)});await userEvent.click(screen.getByRole("button",{name:"Check for invitation changes"}));expect(await screen.findByRole("alert")).toHaveTextContent(/earlier invitation/);expect(screen.getByRole("button",{name:"Copy practice notes"})).toBeDisabled();expect(screen.getByLabelText("What I did")).toHaveValue("My actual contribution.");});
test("source outage preserves inputs and blocks practice until verified",async()=>{mocks.source.mockRejectedValue(new Error("Interview source unavailable."));setup();expect(await screen.findByRole("alert")).toHaveTextContent("Interview source unavailable.");await userEvent.type(screen.getByLabelText("Posting for this role"),posting);await userEvent.click(screen.getByRole("button",{name:"Reload interview source"}));expect(screen.getByLabelText("Posting for this role")).toHaveValue(posting);expect(screen.getByRole("button",{name:"Build my practice"})).toBeDisabled();});
test("failed generation retains inputs and never claims practice exists",async()=>{mocks.build.mockRejectedValue(new Error("The invitation changed."));setup();await fill();await userEvent.click(screen.getByRole("button",{name:"Build my practice"}));expect(await screen.findByRole("alert")).toHaveTextContent("The invitation changed.");expect(screen.getByLabelText("Posting for this role")).toHaveValue(posting);expect(screen.queryByText("Walk through a real example.")).not.toBeInTheDocument();});
test("late generation after leaving cannot cache a pack",async()=>{let finish:(value:unknown)=>void;mocks.build.mockImplementation(()=>new Promise(resolve=>{finish=resolve;}));const page=setup();await fill();await userEvent.click(screen.getByRole("button",{name:"Build my practice"}));await waitFor(()=>expect(mocks.build).toHaveBeenCalled());page.unmount();finish!(pack);await new Promise(resolve=>setTimeout(resolve,0));const cache=page.client.getQueryData<Record<string,{pack?:unknown}>>(["outreach-draft-session","owner","interview-prep"]);expect(cache?.[`${logicalKey}:${dedupeKey}`]?.pack).toBeUndefined();});
test("account switch does not expose another account's posting or notes",async()=>{const page=setup();await fill();await build();await userEvent.type(screen.getByLabelText("Situation"),"Owner private notes.");mocks.auth.mockReturnValue({user:{uid:"other-owner"}});page.rerender(<QueryClientProvider client={page.client}><MemoryRouter><InterviewPrep/></MemoryRouter></QueryClientProvider>);await waitFor(()=>expect(screen.getByLabelText("Posting for this role")).toHaveValue(""));expect(screen.queryByText("Walk through a real example.")).not.toBeInTheDocument();});
test("copy uses the user's actual notes; clipboard failure keeps them editable",async()=>{setup();await fill();await build();await userEvent.type(screen.getByLabelText("What I did"),"I verified appointment times.");const writeText=vi.fn().mockResolvedValue(undefined);Object.defineProperty(navigator,"clipboard",{configurable:true,value:{writeText}});fireEvent.click(screen.getByRole("button",{name:"Copy practice notes"}));await waitFor(()=>expect(writeText).toHaveBeenCalledWith(expect.stringContaining("What I did: I verified appointment times.")));expect(await screen.findByText(/Practice notes copied/)).toBeInTheDocument();writeText.mockRejectedValue(new Error("Blocked clipboard"));fireEvent.click(screen.getByRole("button",{name:"Copy practice notes"}));expect(await screen.findByText(/Copy failed/)).toBeInTheDocument();expect(screen.getByLabelText("What I did")).toHaveValue("I verified appointment times.");});
test("missing action keys do not request any interview or resume data",()=>{setup(undefined,"/interview-prep");expect(screen.getByText(/Open an interview task/)).toBeInTheDocument();expect(mocks.source).not.toHaveBeenCalled();expect(mocks.variants).not.toHaveBeenCalled();});
